version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo_c
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  server:
    build: ./server
    container_name: server_c
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - frontend
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
  frontend:
    build: ./frontend
    container_name: frontend_c
    restart: unless-stopped
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/app/src
  caddy:
    image: caddy/caddy
    container_name: caddy_c
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/caddy_config
volumes:
  mongo-data:
  logs:
  caddy_data:
  caddy_config: